# ai/research/report.py
# -------------------------------------------------------------------
# Phase 10 — Report Generator
# - Creates a PDF (if reportlab available) or HTML fallback
# - Strategy Cards: assumptions, KPIs, and sample trades/weights
#
# Author: AITradeBot

from __future__ import annotations
import os
import json
import pandas as pd
from typing import Dict, List, Optional

# Optional PDF backend
try:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import inch
    _PDF_OK = True
except Exception:
    _PDF_OK = False


def _fmt_pct(x: float) -> str:
    try:
        return f"{x*100:.2f}%"
    except Exception:
        return "-"


def _fmt(x: float) -> str:
    try:
        return f"{x:.3f}"
    except Exception:
        return "-"


def generate_report(summary_json_path: str, out_pdf_path: Optional[str] = None) -> str:
    """
    Builds a compact strategy report.
    Returns path to report (PDF if possible, else HTML).
    """
    base_dir = os.path.dirname(summary_json_path)
    with open(summary_json_path, "r") as f:
        summary = json.load(f)

    folds_csv = summary.get("fold_results_csv")
    folds_df = pd.read_csv(folds_csv)
    title = f"AITradeBot Research Report — {summary.get('run_id')}"

    if _PDF_OK and out_pdf_path:
        _make_pdf(title, summary, folds_df, out_pdf_path)
        return out_pdf_path
    else:
        out_html = os.path.join(base_dir, "report.html")
        _make_html(title, summary, folds_df, out_html)
        return out_html


def _make_pdf(title: str, summary: Dict, folds_df: pd.DataFrame, out_path: str):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    c = canvas.Canvas(out_path, pagesize=LETTER)
    w, h = LETTER

    def line(y, txt, size=12):
        c.setFont("Helvetica", size)
        c.drawString(0.8*inch, y, txt)
        return y - 0.22*inch

    y = h - 0.9*inch
    y = line(y, title, 16)
    y = line(y, f"Symbols: {', '.join(summary['symbols'])}")
    y = line(y, f"Period/Interval: {summary['period']} / {summary['interval']}")
    y = line(y, f"Folds: {summary['folds']}")
    y = line(y, f"Avg Sharpe: {_fmt(summary['avg_sharpe'])} | Avg Ret: {_fmt_pct(summary['avg_ret'])} | Avg MDD: {_fmt_pct(summary['avg_mdd'])}")
    y -= 0.2*inch
    y = line(y, "Fold KPIs:", 14)

    header = ["Fold","Sharpe","Ret","MDD","Turnover","Train → Test"]
    y = line(y, "  " + " | ".join(header))
    for _, r in folds_df.iterrows():
        row = [
            int(r["fold_id"]),
            _fmt(r["sharpe"]),
            _fmt_pct(r["ret"]),
            _fmt_pct(r["mdd"]),
            _fmt(r["turnover"]),
            f"{r['train_start']}→{r['train_end']}  /  {r['test_start']}→{r['test_end']}",
        ]
        y = line(y, "  " + " | ".join(map(str, row)))
        if y < 1.2*inch:
            c.showPage()
            y = h - 0.9*inch

    c.showPage()
    c.save()


def _make_html(title: str, summary: Dict, folds_df: pd.DataFrame, out_path: str):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    rows = []
    for _, r in folds_df.iterrows():
        rows.append(f"""
            <tr>
              <td>{int(r['fold_id'])}</td>
              <td>{_fmt(r['sharpe'])}</td>
              <td>{_fmt_pct(r['ret'])}</td>
              <td>{_fmt_pct(r['mdd'])}</td>
              <td>{_fmt(r['turnover'])}</td>
              <td>{r['train_start']}→{r['train_end']} / {r['test_start']}→{r['test_end']}</td>
            </tr>
        """)
    html = f"""
    <html>
    <head>
    <title>{title}</title>
    <style>
      body {{ font-family: Arial, sans-serif; padding: 20px; }}
      table {{ border-collapse: collapse; width: 100%; }}
      th, td {{ border: 1px solid #ddd; padding: 8px; }}
      th {{ background: #f2f2f2; }}
    </style>
    </head>
    <body>
      <h2>{title}</h2>
      <p><b>Symbols:</b> {", ".join(summary['symbols'])}</p>
      <p><b>Period/Interval:</b> {summary['period']} / {summary['interval']}</p>
      <p><b>Folds:</b> {summary['folds']}</p>
      <p><b>Avg Sharpe:</b> {_fmt(summary['avg_sharpe'])} &nbsp; | &nbsp;
         <b>Avg Ret:</b> {_fmt_pct(summary['avg_ret'])} &nbsp; | &nbsp;
         <b>Avg MDD:</b> {_fmt_pct(summary['avg_mdd'])}</p>
      <h3>Fold KPIs</h3>
      <table>
        <tr>
          <th>Fold</th><th>Sharpe</th><th>Ret</th><th>MDD</th><th>Turnover</th><th>Train → Test</th>
        </tr>
        {''.join(rows)}
      </table>
      <p style="margin-top:24px;color:#666;">Generated by AITradeBot Research Harness.</p>
    </body>
    </html>
    """
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
