# ai/policy/bundle_writer.py

from __future__ import annotations
import json
import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger("PolicyBundleWriter")


def write_policy_bundle(trainer: Any, out_dir: Path, policy_name: str, version: str):
    """
    Create a policy bundle folder:

        <out_dir>/
          model.zip or model.npy
          manifest.json

    - Prefer copying trainer.cfg.save_to/model.zip
    - Fallback to saving numpy weights from trainer.get_model_weights()
    """

    out_dir.mkdir(parents=True, exist_ok=True)

    model_file = None

    # 1) Try copying SB3 model.zip
    src_model = None
    try:
        cfg = getattr(trainer, "cfg", None)
        if cfg is not None:
            candidate = cfg.save_to / "model.zip"
            if candidate.exists():
                src_model = candidate
    except Exception:
        src_model = None

    if src_model is not None:
        dst = out_dir / "model.zip"
        shutil.copy2(src_model, dst)
        model_file = dst.name
        logger.info("💾 Copied trained model → %s", dst)
    else:
        # 2) Fallback to numpy weights
        if hasattr(trainer, "get_model_weights"):
            weights = trainer.get_model_weights()
            dst = out_dir / "model.npy"
            np.save(dst, weights)
            model_file = dst.name
            logger.info("💾 Saved model weights array → %s", dst)
        else:
            logger.warning("No model artifact found to save in bundle.")

    manifest = {
        "policy_name": policy_name,
        "version": version,
        "created_at": datetime.utcnow().isoformat(),
        "model_file": model_file,
        "files": [f for f in [model_file, "metrics.json"] if f],
        "description": "Auto-generated by Phase56 replay training",
    }

    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    logger.info("📝 Saved manifest → %s", manifest_path)

    return manifest_path, True
